### ISSUE TITLE
Analysis diagram

### ISSUE THREAD

**Issue by Fungtu** [prabhathc/2340#11]
Each person will take their individual detailed user story from M4, and create a robustness/analysis diagram from it. (again, you do not have to cover for a team mate, just do your own). The diagram should show interaction between the system and your actors using the 4 symbols we discussed in class (boundary, control, etity, external actor). An example diagram is here: external link: http://www.math-cs.gordon.edu/courses/cs211/ATMExample/AnalysisClasses.html

**Comment by iaraneta** [comment]
![img_9221](https://user-images.githubusercontent.com/31486274/31106420-91948cda-a7b9-11e7-8ec0-73d107ebd3e8.JPG)
